[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
async-stream = { workspace = true }
clap = { workspace = true }
common = { workspace = true }
fastrand = { workspace = true }
tokio ={ workspace = true }
tonic = { workspace = true }
tonic-health = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
